import { Box, Button, Dialog, DialogActions, DialogContent, DialogTitle, MenuItem, TextField } from '@mui/material';
import { useState } from 'react';
import type { Spell } from '../../../../api';
import { damageIcons } from '../select-class/class-configuration/constants';

interface Props { open: boolean; onClose: () => void; onAdd: (spell: Spell, cantrip: boolean) => void; }
export const CustomSpellDialog = ({ open, onClose, onAdd }: Props) => {
  const [name, setName] = useState(''); const [level, setLevel] = useState('Заговор'); const [school, setSchool] = useState(''); const [description, setDescription] = useState(''); const [damageDice, setDamageDice] = useState(''); const [damageType, setDamageType] = useState(''); const [isCustomDamageType, setIsCustomDamageType] = useState(false);
  const submit = () => { if (!name.trim() || !description.trim()) return; const cantrip = level === 'Заговор'; onAdd({ _id: `custom-${crypto.randomUUID()}`, name: name.trim(), level, school, description: description.trim(), damage_dice: damageDice || null, damage_type: damageType || null, casting_time: '', range: '', components: '', duration: '', classes: [], subclasses: [], category: 'custom', source: 'Пользовательское', url: '' }, cantrip); setName(''); setDescription(''); onClose(); };
  const selectDamageType = (value: string) => { setIsCustomDamageType(value === '__custom__'); setDamageType(value === '__custom__' ? '' : value); };
  return <Dialog open={open} onClose={onClose} fullWidth maxWidth="sm"><DialogTitle>Создать заклинание</DialogTitle><DialogContent sx={{ display: 'grid', gap: 2, pt: '16px !important' }}><TextField label="Название" value={name} onChange={(e) => setName(e.target.value)} required autoFocus /><TextField select label="Уровень" value={level} onChange={(e) => setLevel(e.target.value)}>{['Заговор', '1', '2', '3', '4', '5', '6', '7', '8', '9'].map((item) => <MenuItem key={item} value={item}>{item}</MenuItem>)}</TextField><TextField label="Школа магии" value={school} onChange={(e) => setSchool(e.target.value)} /><TextField label="Урон" value={damageDice} onChange={(e) => setDamageDice(e.target.value)} placeholder="например, 2к6" /><TextField select label="Тип урона" value={isCustomDamageType ? '__custom__' : damageType} onChange={(e) => selectDamageType(e.target.value)}><MenuItem value="">Без урона</MenuItem>{Object.keys(damageIcons).map((type) => <MenuItem key={type} value={type}><Box component="img" src={damageIcons[type]} alt="" sx={{ width: 20, height: 20, mr: 1, verticalAlign: 'middle' }} />{type}</MenuItem>)}<MenuItem value="__custom__">Свой тип…</MenuItem></TextField>{isCustomDamageType && <TextField label="Свой тип урона" value={damageType} onChange={(e) => setDamageType(e.target.value)} required autoFocus />}<TextField label="Описание" value={description} onChange={(e) => setDescription(e.target.value)} required multiline minRows={5} /></DialogContent><DialogActions><Button onClick={onClose}>Отмена</Button><Button variant="contained" onClick={submit} disabled={!name.trim() || !description.trim()}>Добавить</Button></DialogActions></Dialog>;
};
